mybatis:
  mapper-locations: classpath:/Mapper/*Mapper.xml
  type-aliases-package: com.test.hy.test.books.Entity

server:
  port: 18080


spring:
  datasource:
    username: root
    password: huangyang
    url: jdbc:mysql://localhost:3306/test_books?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
